default: ch_18_transactions_2-book.pdf ch_18_transactions-book.pdf

ch_18_transactions_2-book.pdf: ch_18_transactions_2.pdf
	pdfbook --short-edge $<

ch_18_transactions-book.pdf: ch_18_transactions.pdf
	pdfbook --short-edge $<
